version: '3.8'
services:
  postgres:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_DB: whatsapp_bot
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: senha_segura
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis:6
    restart: always
    command: ["redis-server", "--requirepass", "senha_redis"]
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
  minio:
    image: minio/minio
    restart: always
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
    command: server /data
    volumes:
      - miniodata:/data
volumes:
  pgdata:
  redisdata:
  miniodata:
