apiVersion: v1
kind: Secret
metadata:
  name: whatsapp-bot-secrets
type: Opaque
stringData:
  # Sentry
  SENTRY_DSN: ""
  SENTRY_ENV: "production"
  SENTRY_RELEASE: ""

  # PostgreSQL
  DB_HOST: "postgres"
  DB_PORT: "5432"
  DB_NAME: "whatsapp_bot"
  DB_USER: "postgres"
  DB_PASS: ""

  # Redis (ou URL única)
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  REDIS_PASSWORD: ""
  # REDIS_URL: "redis://:senha@redis:6379"
  # UPSTASH_REDIS_URL: ""
  # UPSTASH_REDIS_PASSWORD: ""

  # OpenAI / NLP
  OPENAI_API_KEY: ""
  HUGGINGFACE_API_KEY: ""

  # E-mail (Nodemailer)
  EMAIL_HOST: "smtp.seuprovedor.com"
  EMAIL_PORT: "587"
  EMAIL_USER: ""
  EMAIL_PASS: ""
  EMAIL_FROM: "bot@empresa.com"

  # SMS (Twilio)
  TWILIO_SID: ""
  TWILIO_TOKEN: ""
  TWILIO_PHONE: ""

  # Dashboard/Integrações
  DASHBOARD_URL: "https://seu-frontend.com"
  DASHBOARD_TOKEN: ""
  DASHBOARD_API_KEY: ""
  DASHBOARD_TIMEOUT: "5000"
  DASHBOARD_RETRIES: "3"

  # Alertas
  ALERT_EMAIL: "alertas@empresa.com"
  ALERT_EMAIL_FROM: "bot@empresa.com"
  ALERT_EMAIL_PASS: ""
  WHATSAPP_ALERT_API_URL: ""
  WHATSAPP_ALERT_TO: ""
  TELEGRAM_BOT_TOKEN: ""
  TELEGRAM_ALERT_CHAT_ID: ""
  SLACK_WEBHOOK_URL: ""

  # Storage (MinIO/S3)
  STORAGE_ENDPOINT: "minio"
  STORAGE_PORT: "9000"
  STORAGE_ACCESS_KEY: "minioadmin"
  STORAGE_SECRET_KEY: "minioadmin"
